### ISSUE TITLE
Memory leakage in Quartz

### ISSUE THREAD

**Issue by cyberiums** [ronaldoussoren/pyobjc#303]
Hi,

I am trying to debug an issue of successive application state collection with user activity. But I get a very bad memory leakage with every iteration to find top window and it's metadata.
Is there a way to release memory after getting the required info from objects.?

```
from memory_profiler import profile
import sys, time, Quartz, gc

def _get_active_window():
    k  = 0
    windows = Quartz.CGWindowListCopyWindowInfo(Quartz.kCGWindowListExcludeDesktopElements | Quartz.kCGWindowListOptionOnScreenOnly, Quartz.kCGNullWindowID)
    lwin = list(windows)
    del windows
    for win in range(len(lwin)):
        if lwin[win]['kCGWindowLayer'] == 0:
            #store lwin and move
            break

    return k

@profile
def main(n):
    for i in range(n):
        k = _get_active_window()

for i in range(100):
    main(10*i)
    gc.collect()

```

**Comment by ronaldoussoren** [comment]
A quick workaround is to create a new NSAutoreleasePool before the call to _get_active_window and delete it afterwards.  That avoids this problem on my machine:

```python
def main(n):
    for i in range(n):
        with objc.autorelease_pool():
            k = _get_active_window()
```

This is needed because the value 'kCGWindowLayer' is proxied to a Cocoa NSString,  and that proxy object is autoreleased. 

A Cocoa Runloop will automatically flush that pool once through the loop, the workaround above does something similar. 

P.S. The conversion to a python list (`lwin = list(windows)`) is not necessary.
