### ISSUE TITLE
Foundation Error for Quartz

### ISSUE THREAD

**Issue by SLey3** [ronaldoussoren/pyobjc#304]
I was using the module [pynput](https://github.com/moses-palmer/pynput/issues/260) which uses quartz/foundation. But when I ran my code that uses this module, I ran into an error that can be described in the link below and it involves `NSPoint`. 
[Attribute error](https://stackoverflow.com/questions/61670524/how-to-fix-a-traceback-and-attributeerror-when-it-involves-a-module)

**Comment by ronaldoussoren** [comment]
- What version of pyobjc is installed?
- What version of macOS is used?
- What version of Python is used?

- Does "from Foundation import NSPoint" work?

**Comment by SLey3** [comment]
- MacOs Version: 10.15.4
- Pynput Version: 1.0.4
- Python version: 3.8
- Does “from foundation import NSPoint” work?
no

**Comment by ronaldoussoren** [comment]
Odd. I don't get errors, but pynput doesn't work for me at all (I've installed it using pip and tried a number of scripts from the readme file).

```
$ pip list
Package                 Version
----------------------- -------
pip                     19.2.3 
pynput                  1.6.8  
pyobjc-core             6.2    
pyobjc-framework-Cocoa  6.2    
pyobjc-framework-Quartz 6.2    
setuptools              41.2.0 
six                     1.14.0 
```

I do notice that I'm using a newer version of pynput than you, but even if I force installation of that version I don't get any errors (the tool still doesn't work, probably because of a macOS security setting).

BTW. It's "from Foundation import NSPoint", not "from foundation import NSPoint" (note the capital F).

**Comment by SLey3** [comment]
Yeah, thank you anyways but I've changed to [keyboard](https://pypi.org/project/keyboard/) module which also uses quartz/NSPoint and that module works as pynput didn't work and it had specific function that I needed.

Thank you anyways,
Sergio Ley
