### ISSUE TITLE
Overriding some selector types appear to have no effect

### ISSUE THREAD

**Issue by dany74q** [ronaldoussoren/pyobjc#324]
Hey @ronaldoussoren !

First of all - what an awesome library, kudos for all the hard work.

I've tackled an interesting situation on my machine, where I'm trying to invoke the `LocalAuthentication::LAContext::evaluateAccessControl:operation:localizedReason:reply:` instance method.

The first explicit argument it takes is a `^{__SecAccessControl=}`, and I couldn't successfully invoke it, 
getting a `ValueError: depythonifying 'pointer', got 'SecAccessControlRef'`.

Reproducer:
```
from LocalAuthentication import LAContext, LAAccessControlOperationCreateKey
from Security import SecAccessControlCreateWithFlags, kSecAttrAccessibleWhenUnlocked, kSecAccessControlUserPresence

auth_ctx = LAContext.new()
access_control = SecAccessControlCreateWithFlags(None, kSecAttrAccessibleWhenUnlocked, kSecAccessControlUserPresence, None)[0]

auth_ctx.evaluateAccessControl_operation_localizedReason_reply_(access_control, LAAccessControlOperationCreateKey, 'test', lambda x, y: print(x))
```

My first instinct was to cast the `SecAccessControlRef` to a ctypes pointer, but I couldn't really figure out how to do that.
edit: I believe `cyptes.cast(objc.pyobjc_id(access_control), ctypes.c_void_p)` does the casting, but passing variations of this to the function hand't worked either.

My fallback was to tweak the metadata of the method with `objc.registerMetaDataForSelector`,
but I wasn't able to change the first argument's type - only it's modifier and other attributes.

Reproducer:
```
import objc
objc.registerMetaDataForSelector(b'LAContext', b'evaluateAccessControl:operation:localizedReason:reply:', { 'arguments': { 2: { 'type': b'i', 'type_modifier': 'o' }}})

LAContext.evaluateAccessControl_operation_localizedReason_reply_.__metadata__()

# Notice how the type stays the same, but my modifier registers successfully
Out:
{'retval': {'_template': True, 'type': b'v'},
 'arguments': ({'_template': True, 'type': b'@'},
  {'_template': True, 'type': b':'},
  {'type': b'o^{__SecAccessControl=}', 'null_accepted': True},
  {'_template': True, 'type': b'q'},
  {'_template': True, 'type': b'@'},
  {'_template': True, 'type': b'@?'}),
 'classmethod': False,
 'hidden': False}
```

I'm probably doing something incorrectly - I could really use your help for figuring out how to
invoke the method, or change the signature for the first argument.

Thanks a lot, appreciate your time !

**Comment by ronaldoussoren** [comment]
There are two issues here:

1) For some reason registerMetadataForSelector doesn't work here, even if I change the type. There's one reason the change you use doesn't work: sizeof(int) != sizeof(void*).  But even changing the argument type to b"@" (which is more correct) doesn't work for me.   I think that's because the bindings for LocalAuthentication already register metadata for this selector, and that's used instead of the additional information. Either merging the two sets of data, or raising an error would give a better user experience. I'll try to implement this for PyObjC 7.

2) Passing an SecAccessControl object should just work, but doesn't because the Security bindings don't register ``^{__SecAccessControl=}`` as a CoreFoundation type (because I created those bindings manually due to problems with the tool I use).  I'm working on cleaning up that tool for PyObjC 7 and and hopeful that this will allow me to fully generate the metadata for the Security bindings, which should fix this issue.


Adding the following code to the script works around issue (2) and fixes the exception you were getting (but...):
```
from Security import SecAccessControlGetTypeID
objc.registerCFSignature("SecAccessControlRef", b"^{__SecAccessControl=}", SecAccessControlGetTypeID())
```

That said, with this addition your script now crashes hard for me in the call to evaluateAccessControl... (SIGILL). I haven't tried to debug that yet.

The crash was in a bigsur test vm, so ymmv.

**Comment by dany74q** [comment]
Ah - that's fantastic, thanks for the prompt response !

My interpreter had segfaulted until I've added the following metadata change (which did register successfully, for some reason):

```
objc.registerMetaDataForSelector(b'LAContext', b'evaluateAccessControl:operation:localizedReason:reply:', 
    { "arguments": { 5: { "callable": {
        "retval": {"type": b"v"}, 
        "arguments": { 
            0: { "type": b"^v"}, 
            1: {"type": b"Z"}, 
            2: {"type": b"@"}
        }
    }}}}
)
```

Now the invocation works as expected.

Thanks for the help !

I wasn't sure if you'd like to keep the ticket open for reference to the v7 improvements, feel free to close it.

**Comment by ronaldoussoren** [comment]
Great to hear. I'm leaving the issue open as a reminder that I need to implement a proper fix.
