### ISSUE TITLE
install pyobjc for multiple os versions.

### ISSUE THREAD

**Issue by weswhet** [ronaldoussoren/pyobjc#354]
Hi, I work with the https://github.com/saltstack/salt project and we are trying to include pyobjc into the project. right now when we attempt to add pyobjc through pip `pyobjc==6.2.2` it only includes the additional frameworks for the os version it's built on which in this case is 10.14 which makes sense. 

Is there a way to install pyobjc and have it include all of the frameworks for a list of supported os_versions?  In this case 10.14-11.0? Outside of specifically listing all of the frameworks in `requirements.txt`?

**Comment by weswhet** [comment]
This is related to https://github.com/saltstack/salt/issues/60012

**Comment by ronaldoussoren** [comment]
I'm afraid the only way to install all frameworks wrappers is to install them manually, the "pyobjc" wrapper package is designed to install the subset of packages that are relevant for the current machine.  That's the most common use case, and avoid bug reports about not being able to use a framework wrapper on a version of macOS that doesn't have that framework.

The metadata in binary wheels does not, and will not, forbid installing wheels on systems that don't have the required system framework.  Building from source does enforce this, but that's because C extensions cannot be build without having the wrapped framework available.

**Comment by ronaldoussoren** [comment]
IMHO this could and should be feature in pip. I've therefore filed an issue for this with that project.

**Comment by ronaldoussoren** [comment]
I think I can provide support for this in PyObjC by using the extras feature, something like:

```
$ pip install pyobjc[allbindings]
```

I'll probably add this feature in PyObjC 8 ("this fall")
