### ISSUE TITLE
M1 Mac supports

### ISSUE THREAD

**Issue by orklann** [ronaldoussoren/pyobjc#369]
Does PyObjc support M1 Mac now? And if yes, do I need to provide two version of my app (One for Intel, one for M1) which uses PyObjc?

**Comment by ronaldoussoren** [comment]
Yes and no ;-)

PyObjC supports M1 Mac, and has done so since the release of Big Sur.  The wheels on PyPI are fat binaries that support both arm64 and x86_64, as does the "universal2" installer for python on www.python.org.

py2app also supports fat binaries out of the box.

That said, not all projects on PyPI have universal wheels. Some projects only provide per-architecture wheels.

**Comment by orklann** [comment]
Yeah, I see, thank you for your hard works.
