### ISSUE TITLE
use void* in function signature?

### ISSUE THREAD

**Issue by hiaselhans** [ronaldoussoren/pyobjc#380]
Hello, thanks for the good library!

i want to make a delegate for an rfcomm connection. When i implement the corresponding function i end up with segfaults even when i'm doing nothing in the function call:

https://developer.apple.com/documentation/iobluetooth/iobluetoothrfcommchanneldelegate/1431822-rfcommchanneldata?language=objc

``` python
def rfcommChannelData_data_length_(self, channel, data, length):
    return
```

is there a decorator to transform a data-pointer with length to a buffer type? or similar?

thanks!

**Comment by ronaldoussoren** [comment]
The best way to accomplish this is through the metadata system, there is a decorator that can be used to change the default method signature but that interface is not rich enough in this case.  The crash your getting is because the bridge by default assumes that all arguments are Objective-C objects (``id``).

With decorator:

```
class MyDelegate (NSObject):
    @objc.typedSelector(b"v@:@^vQ")
    def rfcommChannelData_data_length_(self, channel, data, length):
           pass
```

The problem with this approach is that the ``data`` argument will be passed in as an integer because the bridge doesn't know it is actually a buffer.

To fix that, drop the decorator and register some metadata before defining the class:

```
objc.registerMetaDataForSelector(
    b"NSObject",   # Name of the class, I use NSObject for selectors from protocols to automatically do the right thing
    b"rfcommChannelData:data:length:",   # Selector name
    {
       "arguments": {
         3: { "type": "b"n^v", "c_array_length_in_arg": 4 },  # 0, 1 are implicit arguments, 2 is ``channel``, 3 is ``data``
         4: { "type": b"Q" } # ``length``
    }
)
```

Note: I wrote the code fragments above directly in the browser, there may be typos.

BTW. I might implement full bindings for the. IOBluetooth framework in the future, although that depends on how much work that ends up being.

**Comment by hiaselhans** [comment]
wow, thats responsive! and did the job :) thanks a lot!

now, another quick question:

i need to call [writeSync](https://developer.apple.com/documentation/iobluetooth/iobluetoothrfcommchannel/1434633-writesync)

``` objc
func writeSync(_ data: UnsafeMutableRawPointer!, 
        length: UInt16) -> IOReturn
```

i thought i need to make a pointer with objc.context, is that correct?

``` python
  def synchronouslyWriteData_toRFCOMMChannel_(self, data, channel):
      #     return [channel writeSync:(void *)[data bytes] length:[data length]];
      pointer =  objc.context.register(data)
      result = channel.writeSync_length_(pointer, len(data))

      objc.context.unregister(pointer)

      return result
```

here, data is a bytes object and the call is unfortionately not writing the right data.

**Comment by ronaldoussoren** [comment]
You don't want to use ``objc.context``, that's a basic registry for passing "context info" pointers.

In this case you want to do something similar to the registration for the protocol method, but with slightly less information because PyObjC can extract the basic type information from the ObjC runtime.

```
objc.registerMetaDataForSelector(
    b"IOBluetoothRFCOMMChannel", 
    b"writeSync:length:",   # Selector name
    {
       "arguments": {
         2: { "type_modifier": "b"n", "c_array_length_in_arg": 4 },
       }
     }
)
```

You can also use ``objc._C_IN`` instead of ``b"n"``, that's pobably slightly clearer.

**Comment by hiaselhans** [comment]
ok thanks!

still i seem to not have it right. I am cleaning up my fork of pybluez to get rid of objc-libraries included in the package:

https://github.com/hiaselhans/pybluez2/blob/master/bluetooth/macos/btsocket/delegate.py

i figured length: UInt16 being a half argument i had to use _C_USHT but that didn't help either.
i am getting a timeout error on the remote device so i guess not all / wrong data is sent

**Comment by hiaselhans** [comment]
and actually data is of type `<objective-c class _NSInlineData at 0x7fff8a9f12d0>`

**Comment by hiaselhans** [comment]
got it!

thanks a lot for all the help
