### ISSUE TITLE
Memory crash?

### ISSUE THREAD

**Issue by schriftgestalt** [ronaldoussoren/pyobjc#383]
I get somehow random crashes when calling into python from ObjectiveC. The traceback is below. I narrowed it down in the python code and the crash happens roughly in the same area of the code but not exactly the same line. All I can think of is that this is a tight loop where a lot objects are created. 

I know this is a long shot, but maybe someone has an idea?

The crash is around this line: https://github.com/yanone/speedpunk/blob/7a9fbbd956bdd853f83680fe66014926fc90b50e/SpeedPunk.glyphsReporter/Contents/Resources/speedpunk/speedpunklib.py#L683

```
#0	0x0000000129bc03aa in visit_decref ()
#1	0x0000000129a33c5e in dict_traverse ()
#2	0x0000000129bbe944 in gc_collect_main ()
#3	0x0000000129bc0c12 in _PyObject_GC_Alloc ()
#4	0x0000000129a771de in PyType_GenericAlloc ()
#5	0x0000000129a73bf5 in type_call ()
#6	0x00000001299eb3c6 in _PyObject_MakeTpCall ()
#7	0x0000000129b291cb in call_function ()
#8	0x0000000129b1f5c2 in _PyEval_EvalFrameDefault ()
#9	0x0000000129b18b93 in _PyEval_Vector ()
#10	0x00000001299eb640 in _PyObject_FastCallDictTstate ()
#11	0x0000000129a7d9c8 in slot_tp_init ()
#12	0x0000000129a73cf4 in type_call ()
#13	0x00000001299eb3c6 in _PyObject_MakeTpCall ()
#14	0x0000000129b291cb in call_function ()
#15	0x0000000129b1f5c2 in _PyEval_EvalFrameDefault ()
#16	0x0000000129b18b93 in _PyEval_Vector ()
#17	0x0000000129b290b2 in call_function ()
#18	0x0000000129b1f51c in _PyEval_EvalFrameDefault ()
#19	0x0000000129b18b93 in _PyEval_Vector ()
#20	0x0000000129b290b2 in call_function ()
#21	0x0000000129b1f51c in _PyEval_EvalFrameDefault ()
#22	0x0000000129b18b93 in _PyEval_Vector ()
#23	0x00000001299ef9ae in method_vectorcall ()
#24	0x0000000129b290b2 in call_function ()
#25	0x0000000129b20c94 in _PyEval_EvalFrameDefault ()
#26	0x0000000129b18b93 in _PyEval_Vector ()
#27	0x000000012a741f37 in method_stub ()
#28	0x00007fff6d55e9ea in ffi_closure_unix64_inner ()
#29	0x00007fff6d55e0ee in ffi_closure_unix64 ()
#30	0x00000001000f0b5c in -[GSSomeObject someMethod:]
```

**Comment by ronaldoussoren** [comment]
These are pretty hard to debug, the crash is while cleaning up a cycle in CPython's cyclic garbage collector.  "Some" object has a bad reference or reference count and that's causing problems. The line where this crashes is mostly unrelated to the crash itself, that's just the place where the cyclic garbage collector is triggered.

The only way I've found to debug stuff like this is with a C debugger: Run the application in the debugger and inspect the stack when the crash happens.   Note that you will have to make sure that the main binary is either unsigned, or is signed without using the hardened runtime, because otherwise LLDB won't be able to debug the code (annoyingly).

**Comment by schriftgestalt** [comment]
I actually found the problem. This two lines of code helped a lot:
```
import tracemalloc
tracemalloc.start()
```

**Comment by ronaldoussoren** [comment]
Great!   I didn't know tracemalloc exists, a nice new tool.
