### ISSUE TITLE
Avoid linking to the Carbon framework?

### ISSUE THREAD

**Issue by leofang** [ronaldoussoren/pyobjc#390]
Hi, not sure if this is possible: When debugging https://github.com/conda-forge/pyobjc-framework-metal-feedstock/issues/5 for Conda-Forge's build of `pyobjc-core`, I noticed the root cause was that Conda-Forge's compiler added `-Wl,-dead_strip_dylibs` to the linker flag, and because Carbon is not explicitly used in any pyobjc module, it's considered over-linking and removed by the linker, causing the reported misbehavior.

My question is: It looks like Carbon has been marked deprecated for several years, is it possible for pyobjc to link more explicitly so that we can safely remove the two lines below?
https://github.com/ronaldoussoren/pyobjc/blob/6accbfc89b6b0f1d36a7c2d651afb9667f30b639/pyobjc-core/setup.py#L100-L101
Thanks!

**Comment by ronaldoussoren** [comment]
Interesting... 

I'll have to debug to find why (effectively) removing "-framework Carbon" causes problems in this way, and to be honest I don't know why pyobjc-core is linked to Carbon in the first place. 

I can reproduce the problem on my system, removing "-framework Carbon" from pyobjc-core gives the same behaviour (``Metal.MTLCreateSystemDefaultDevice()`` returns ``None``). 

BTW. A large part of Carbon is deprecated, but not everything.

**Comment by ronaldoussoren** [comment]
Interestingly the same behaviour can be seen in Objective-C:

```Objective-C
#import <Metal/Metal.h>
#import <Foundation/Foundation.h>

int main(void)
{
    NSLog(@"%@", MTLCreateSystemDefaultDevice());
}
```

I guess the next step is to create a small Xcode project that does something similar and check if that makes a difference.  But not today...

Link this with "-framework Foundation -framework Metal" and this prints ``(null)``. Link with "-framework Carbon" as well and this prints a Metal device. 


BTW. I note that the condaforge recipe for pyobjc-core mentions an intention to switch to the copy of libffi included with CF. Please don't.

**Comment by ronaldoussoren** [comment]
I've done some more research, it looks like there's an implicit dependency between Metal and a low-level library, in particular the program above prints a device value when linked to CoreGraphics instead of Carbon.  It also works when linking with AppKit.

In PyObjC 8 I will:
- Remove "-framework Carbon" from pyobjc-core
- Add "import AppKit" to the Metal bindings

When not linking with Carbon the "import Metal; print(Metal.MTLCreateSystemDefaultDevice())" prints None; and "import Metal, AppKit; print(Metal.MTLCreateSystemDefaultDevice())" prints a device. The change above should therefore fix the issue for PyObjC 8.

I'm keeping this issue open until this change actually ends up in the repository.

**Comment by leofang** [comment]
> except for osx-arm64 builds, which have not switched over yet

I think with https://github.com/conda-forge/libffi-feedstock/pull/36 we are about to ready to switch over.
