### ISSUE TITLE
Bindings for TranslationUIServices framework

### ISSUE THREAD

**Issue by jankais3r** [ronaldoussoren/pyobjc#397]
Hi,

I was wondering whether it is technically possible to add support for Monterey's TranslationUIServices framework.

The framework is located in `/System/Library/PrivateFrameworks/TranslationUIServices.framework` and it handles online/offline translations requested by the user from various applications. E.g., it can be triggered by selecting a foreign text in TextEdit and choosing "Translate…" from the context menu.

**Comment by jankais3r** [comment]
To answer my own question, all Translation-related frameworks seem to contain Objective-C classes.

```python
import objc

Translation = {}
objc.loadBundle("Translation", Translation, bundle_path = objc.pathForFramework(u'/System/Library/PrivateFrameworks/Translation.framework'))
TranslationUI = {}
objc.loadBundle("TranslationUI", TranslationUI, bundle_path = objc.pathForFramework(u'/System/Library/PrivateFrameworks/TranslationUI.framework'))
TranslationUIServices = {}
objc.loadBundle("TranslationUIServices", TranslationUIServices, bundle_path = objc.pathForFramework(u'/System/Library/PrivateFrameworks/TranslationUIServices.framework'))

print(len(Translation))
print(len(TranslationUI))
print(len(TranslationUIServices))
```

```
17037
22028
22141
```

**Comment by ronaldoussoren** [comment]
Technically it should be possible when, as you write, this framework contains Objective-C classes.  Because this is a private API I won't add bindings to PyObjC itself though.

Because there's no metadata you don't have to use ``objc.loadBundle``, but can also use ``NSBundle`` to load these frameworks, for example:

```
import Foundation
Foundation.NSBundle.bundleWithPath_("/System/Library/PrivateFrameworks/Translation.framework").load()
```

Look for the classes you want to use using ``objc.lookUpClass(NAME)``, or get all classes in the process using ``objc.getClassList()``.
