### ISSUE TITLE
Question how to read keyAEKeyForm

### ISSUE THREAD

**Issue by link89** [ronaldoussoren/pyobjc#398]
Hi, as Python 3 deprecate the Carbon module, I have to turn to pyobjc to make some legacy code work.
In one place I need to use `keyAEKeyForm` but I didn't figure out how.
By search the code I can find it here,
`pyobjc-framework-CoreServices/metadata/raw.AE/x86_64-10.16.fwinfo:   "keyAEKeyForm": 1718579821,`

But how can I use it in the python. I guess it is same where in `CoreServices` but still cannot find it. Can anyone shed some light? Thank you.

**Comment by ronaldoussoren** [comment]
``keyAEKeyForm`` is not exposed in the CoreServices bindings. I did generate a scan of the header files (the file in "raw.AE" you found), but never created the actual bindings. That's likely because those bindings are non-trivial due to the low-level nature of the C API.

I'm leaving this issue open to check how hard it would be to create proper bindings for these APIs.

**Comment by ronaldoussoren** [comment]
Is there a higher level API that you could use instead of this API?  The APIs in ScriptingBridge provide a higher level API for AppleScript and might be an alternative.

**Comment by ronaldoussoren** [comment]
I've looked at the header files in the AE sub framework and creating bindings for those is doable, but not easy.

**Comment by link89** [comment]
Hi @ronaldoussoren thank you for your time on this issue. I choose to use define the constant by myself to workaround this problem.
