### ISSUE TITLE
AppKit.NSRightTextAlignment has wrong value in macOS12 in M1

### ISSUE THREAD

**Issue by schriftgestalt** [ronaldoussoren/pyobjc#401]
It seems that Apple has changed the values in the alignment constants in macOS12 (I only can test on M1 right now).

I think I saw some "correction code" in pyobjc 7.3 but that didn't seem to be effective. 8.0b1 gives the same wrong value.

```
import AppKit
print(AppKit.NSRightTextAlignment)
```
prints "1" (as in all previous versions of macOS)

but doing this in ObjectiveC:
```
NSLog(@"%d", NSRightTextAlignment)
```
prints "2". 

using `AppKit.NSTextAlignmentRight` works fine.

The documentation of `NSTextAlignmentRight ` states:
> **Declaration**
NSTextAlignmentRight = 2
**Discussion**
*Note*
In Mac apps, including apps built with Mac Catalyst, the value of this enumeration case is 1.

But that doesn't seem to be correct in macOS12

**Comment by ronaldoussoren** [comment]
Hmm... I really need to work showing API deprecations in PyObjC, the machinery is mostly there but I haven't updated my tooling yet to generate the data needed to use that machinery.

I'll fix this in the same way as I've done for the newer name.

**Comment by schriftgestalt** [comment]
Just wondering. Would it be possible to load the values from the runtime directly? Or is that too slow?

**Comment by ronaldoussoren** [comment]
That's not possible, C enums are basically a compile-time construct and cannot be introspected at runtime.

Only Objective-C classes and protocols can be fully introspected at runtime (including methods and properties), and that is used by the bridge. I don't use the information for properties yet because of naming conflicts (properties are a separate namespace in ObjC, but would be in the same namespace as methods in Python).

For functions and C variables the actual value is retrieved at runtime, using metadata in the framework wrappers.

For C enums, static constants, and preprocessor macros the metadata contains all information to use them, including the value, because there is no runtime representation of them at all.

I might end up creating C exertions for the metadata in the future which could solve discrepancies like this, but only if that has more advantages than that.  In particular, this could lead to improved startup performance. But for now I'm still focussing on the core bridge for performance improvements, those affect  running code and I'm pretty sure there is a lot of room for improvement there.
