### ISSUE TITLE
Issue with PyObjC and Images

### ISSUE THREAD

**Issue by AdrianHTML** [ronaldoussoren/pyobjc#411]
I am trying to use `Tkinter` with `PyObjC`. I wrote this Image class with help of this stack overflow answer: https://stackoverflow.com/questions/1849636/how-to-draw-a-rounded-nsimage. 
```py
def rounded_corners(image):
    existing_image = image
    existing_size = existing_image.size()
    new_size = NSMakeSize(existing_size.width,existing_size.height)
    composed_image = NSImage.alloc().initWithSize_(new_size).autorelease()
    composed_image.lockFocus()
    NSGraphicsContext.currentContext().setImageInterpolation_(NSImageInterpolationHigh)
    image_frame = NSRectFromCGRect(CGRectMake(0, 0,existing_size.width,existing_size.height))
    clip_path = NSBezierPath.bezierPathWithRoundedRect_xRadius_yRadius_(image_frame,existing_size.width/5,existing_size.height/5)
    clip_path.setWindingRule_(NSEvenOddWindingRule)
    clip_path.addClip()
    image.drawAtPoint_fromRect_operation_fraction_(NSZeroPoint,NSMakeRect(0, 0, new_size.width, new_size.height),NSCompositeSourceOver,1)
    composed_image.unlockFocus()
    return composed_image

class Image:

    def __new__(cls,file_path,size:tuple[int,int],**kwargs):
        img = NSImage.alloc().initByReferencingFile_(file_path)
        #img.setSize_(size)
        if kwargs.get("rounded_corners",True):
           img = rounded_corners(img)
        return img
```
The class works fine just as it is. But there is an error when I to use it in Tkinter. Just by running this code I get an error:
```py
root = tk.Tk()
root.geometry("1000x1000")
Image("ressources/full7.png",size=(199,1),rounded_corners=True)
root.mainloop()
```

The Error: 
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

After searching on stack overflow I found that this had to do something with memory access. While debugging I also found out that the error:
1. Only occurs when hitting the `mainloop()` function.
2. Only occurs when there is a `mainloop()` function.
3. Only occurs when the `rounded_corners` function is called.

**Comment by ronaldoussoren** [comment]
Don't use ``autorelease``. PyObjC manages Objective-C reference counts for you.

**Comment by AdrianHTML** [comment]
> Don't use `autorelease`. PyObjC manages Objective-C reference counts for you.

Thank you for your quick answer. What is autorelease even doing if I may know?

**Comment by ronaldoussoren** [comment]
Objective-C uses reference counting to semi-automaticly manage memory, similarly to the automaticly managed reference counts in the CPython interpreter.  In modern Objective-C code this is generally done by the compiler ("ARC") instead of manually by the programmer.

A special feature of ObjC's reference counting is the use of "auto release pools",  which are a mechanism to decrease the reference count at a later time (generally at the end of the current run through the GUI event loop). This mechanism is needed in ObjC because most APIs return (in CPython's terms) borrowed references, even if the API does not retain a strong reference to the returned object itself.

PyObjC knows about the Objective-C conventions about reference counting and will automaticly increase and decrease the reference count as needed.  The ObjC APIs are available to Python code to handle special cases where an ObjC library does not follow the ObjC convention.

**Comment by AdrianHTML** [comment]
Ah Thank you. I think I understand it now. I will close this issue now because I think everything is said :)
