### ISSUE TITLE
NSSavePanel problems with allowed type extensions.

### ISSUE THREAD

**Issue by AdrianBuzek** [ronaldoussoren/pyobjc#413]
Hi, 
I have this code to open a simple `NSSavePanel`. I tried to customize it by setting the `setAllowedContentTypes_` method to an array of `UTTypes` like in the <a href="https://developer.apple.com/documentation/appkit/nssavepanel/3566857-allowedcontenttypes?language=objc">Apple Documentation</a> said.

```py
save_panel = NSSavePanel.savePanel()
save_panel.setAllowedContentTypes_([UTType.exportedTypeWithIdentifier_("svg")])
save_panel.runModal()
```

When I run it I get this error:
```
allowedContentsTypes : UTType svg does not have a valid preferredFilenameExtension and will be ignored when validating the file name
```

That is weird because when I use the exact same code to create an NSOpenPanel like this:
```py
open_panel = NSOpenPanel.openPanel()
open_panel.setAllowedContentTypes_([UTType.exportedTypeWithIdentifier_("svg")])
open_panel.runModal()
```

everything works just fine and I can only choose from the `.svg` files.
This fact really confused me because the `NSOpenPanel` inherits from the `NSSavePanel`.

**Comment by ronaldoussoren** [comment]
The problem here is that the argument to ``UTType.exportedTypeWithIdentifier_`` should be a UTI string, for SVG that string is ``"public.svg-image"``. When I use that string in the snippet the error goes away.

Also not the different between the result of these two expressions:
* ``UTType.exportedTypeWithIdentifier_("public.svg-image").preferredFilenameExtension()``: returns ``svg``
* ``UTType.exportedTypeWithIdentifier_("sag").preferredFilenameExtension()``: return None
