### ISSUE TITLE
CoreMIDI appears to be broken

### ISSUE THREAD

**Issue by simondemeule** [ronaldoussoren/pyobjc#425]
Under Python 3.9.1, with pyobjc 8.1 under Catalina 10.15.7, it seems CoreMIDI cannot be imported successfully.

The following code gives me an error:

```
import CoreMIDI

CoreMIDI.MIDIRestart()
```

```
Exception has occurred: ImportError
cannot import name '_inlines' from partially initialized module 'CoreMIDI' (most likely due to a circular import) (/Users/username/project/env/lib/python3.9/site-packages/CoreMIDI/__init__.py)
  File "/Users/username/project/restart.py", line 1, in <module>
    import CoreMIDI
```

Quartz and AppKit are not giving me any issues, so I suppose this is specific to the way CoreMIDI is wrapped here.

**Comment by ronaldoussoren** [comment]
That's annoying, the problem is caused by one of the extensions in this wheel not using the limited ABI (and therefore not compatible with most python versions).

As a workaround you can reinstall just the CoreMIDI bindings from source, which does require a compiler.

Something like this should do the trick (after install pyobjc):

```sh
$ pip uninstall pyobjc-framework-CoreMIDI
$ pip install --no-binary ':all:' pyobjc-framework-CoreMIDI
```

This will just rebuild the CoreMIDI bindings, the other components are fine and don't need to be rebuild.

I'll push out a release over the weekend.

**Comment by ronaldoussoren** [comment]
BTW. I've never used the CoreMIDI bindings myself, I'm fairly sure that the bindings are correct but you may run into some rough edges.

**Comment by simondemeule** [comment]
This works! Thank you so much for your quick reply!
