### ISSUE TITLE
HIServices.AXIsProcessTrustedWithOptions raises with 8.1/8.4 working with 7.1

### ISSUE THREAD

**Issue by barak10** [ronaldoussoren/pyobjc#456]
Recently we have upgraded to pyobjc 8.1
Code that is working on 7.1 have started to raise:

```
import HIServices
from ApplicationServices import kAXTrustedCheckOptionPrompt
HIServices.AXIsProcessTrustedWithOptions({kAXTrustedCheckOptionPrompt: True})

```
In 7.1 is pops up the accessibility dialog as expected, but with 8.1/8.4 is raises with:
`objc.internal_error: PyObjC: internal error in PyObjCFFI_ParseArguments at Modules/objc/libffi_support.m:3238: assertion failed: argbuf_cur <= argbuf_len
`

**Comment by ronaldoussoren** [comment]
Thanks. This is a bug in the bindings for this API.

A quick workaround:
* Look for AXIsProcessTrustedWithOption in HIServers/_metadata.py, it should look like this:

  ```"AXIsProcessTrustedWithOptions": (b"Zo^{__CFDictionary=}",),```

* Remove the "o" just before "^". The new version then looks like:
   
   ```"AXIsProcessTrustedWithOptions": (b"Z^{__CFDictionary=}",),```

With this you code no longer raises. 

There will be a bugfix release later this week that will include this fix as well.   This issue will stay open a little longer because the exception itself is wrong as well and that needs further investigation.

**Comment by barak10** [comment]
Thanks so much for your quick response!
Apparently that's what I have:
`
 "AXIsProcessTrustedWithOptions": (
        b"Z^{__CFDictionary=}",
        "",
        {"arguments": {0: {"type_modifier": "o"}}},
    ),
`

**Comment by ronaldoussoren** [comment]
I should have looked more carefully: remove``"type_modifier": "o"`` from this line, that should fix this issue for now.

**Comment by barak10** [comment]
Thanks so much for your prompt fix!
