### ISSUE TITLE
UninitializedDeallocWarning: NSNotification object with postNotification_ is empty and wont work

### ISSUE THREAD

**Issue by leifadev** [ronaldoussoren/pyobjc#458]
# Problem
Having trouble making a notification come up. I believe I am getting the warning because the object `x` I am making in the first place is empty as from print statements. After the failed attempt too, no print statements would show up again too.

`Cocoa.NSNotification.alloc().init_()` is supposed to be an empty notification called by `Cocoa.NSNotificationCenter.alloc().postNotification_(x)`, but it doesn't work and I get the **UninitializedDeallocWarning** error below:

### Code
```py
@objc.IBAction
def helplink_(self, url):
  x = Cocoa.NSNotification.alloc().init_()
  Cocoa.NSNotificationCenter.alloc().postNotification_(x)
```

### Error
```py
PycharmProjects/shoutout/main.py:77: UninitializedDeallocWarning: leaking an 
uninitialized object of type NSNotificationCenter
  x = Cocoa.NSNotification.alloc().init_()
```

 
Here is working code for launching a NSURL string object...
```py
x = Cocoa.NSURL.alloc().initWithString_(self.gitUrl)
Cocoa.NSWorkspace.alloc().openURL_(x)
```

I am confused on how I can solve this, I will try to figure out a way to use other ones besides `postNotification:` or `initWithName:object:userInfo:`, etc. Any help on what I am doing wrong?

**Comment by ronaldoussoren** [comment]
PyObjC maps Objective-C's method calls directly into Python. Because of this object creation is a two step process, an explicit version of Python's ``__new__`` and ``__init__`` methods, for example:

```python
obj = NSObject.alloc().init()
```

Leaving out the call to an ``init*`` method results in a partially initialised object, hence the ``UninitializedDeallocWarning``. And alternative to using the two-step construction proces is to use one of the factory methods on a class (such as ``Cocoa.NSArray.array()``). 

In your particular case the call to ``postNotification_`` uses the wrong pattern, it should be something like this:

```python
@objc.IBAction
def helplink_(self, url):
    x = Cocoa.NSNotification.alloc().init() # Or probably    x = Cocoa.NSNotification.notificationWithName_object_("hi", 42) 
    Cocoa.NSNotificationCenter.defaultCenter().postNotification_(x) 
```

BTW. I intent to add more pythonic object creation in a future version, hopefully this year. See #275 for the basic idea.

**Comment by leifadev** [comment]
> BTW. I intent to add more pythonic object creation in a future version, hopefully this year. See https://github.com/ronaldoussoren/pyobjc/issues/275 for the basic idea.

What do you mean by exactly making it more pythonic? Meaning allowing things ot be simplified in certain ways, super or subclassing stuff?

**Comment by leifadev** [comment]
Sadly after I wrote the above comment, I got this error
```sh
/Users/ddd/PycharmProjects/shoutout/main.py:73: UninitializedDeallocWarning: leaking an uninitialized object of type NSConcreteNotification
```
