### ISSUE TITLE
objc.BadPrototypeError: Objective-C expects 2 arguments, Python argument has 5 arguments for...

### ISSUE THREAD

**Issue by leifadev** [ronaldoussoren/pyobjc#459]
I got this error when trying to have more then 2 arguments for my notification function.

```
objc.BadPrototypeError: Objective-C expects 2 arguments, Python argument has 5 arguments 
for <unbound selector sendNotif: of appTasks at 0x1066136c0>
```

What does an unbound selector mean?

```py
def sendNotif_(self, title, sender):
    print("NOTI!")
    noti = Cocoa.NSUserNotification.alloc().init()
    noti.setTitle_("title")
```

**Comment by ronaldoussoren** [comment]
"unbound selector" is a method that doesn't have a 'self' argument associated with it (at the moment).  <https://www.geeksforgeeks.org/bound-methods-python/> more or less explains the concept of bound methods.

That's not the important part though.  PyObjC uses a simple algorithm to translate a Python method name into an Objective-C selector (replace "_" by ":"). In Objective-C colons in the selector name are the places where arguments are used.  Your method does not follow this convention, its Objective-C name is "sendNotif:" and that's a selector that expects 1 argument (other than the implicit self argument in ObjC). 

The fix is to add another segment to the name: ``def sendNotificationWithTitle_sender_(self, title, sender): ...``.

See also: https://pyobjc.readthedocs.io/en/latest/core/intro.html

**Comment by leifadev** [comment]
Ahh I see thanks!
