### ISSUE TITLE
How to make CoreWLAN to return bssid?

### ISSUE THREAD

**Issue by Oleksii-Svintsitskyi** [ronaldoussoren/pyobjc#484]
Hello, it's clear now, that in order to obtain `bssid` we have to turn on location services. But it's not clear how to achieve this with such kind of code:
```
from CoreWLAN import CWWiFiClient
iface = CWWiFiClient.sharedWiFiClient().interfaceWithName_("en0")
networks, error = iface.scanForNetworksWithName_error_(
    None,
    None,
)
any_bssid = list(networks)[0].bssid()
iface_bssid = iface.bssid()
```
Please, could you add any documentation about turning on location for CoreWLAN?

**Comment by ronaldoussoren** [comment]
I don't have documentation handy, but in general you can use Apple's Objective-C documentation instead.  Sadly you sometimes need to know what your looking for to be able to find it, and this is one of those cases.

Enabling access to locations requires an app bundle with additional keys in its ``Info.plist`` file, see <https://developer.apple.com/documentation/corelocation/requesting_authorization_for_location_services?language=objc>

When that's done you should be able to use ``CoreLocation.CLLocationManager.new().requestWhenInUseAuthorization()`` to ask for authorization to use location data.  I've checked that this doesn't work in a regular Python installation (without an app bundle), because the bundle in the Python framework doesn't include the keys mentioned earlier (and shouldn't).

If you use py2app you can add the keys like this to your setup.py file (untested code):

```
from setuptools import setup

setup(
    ..., # Normal py2app stuff goes here
    options=dict(
        py2app=dict(
           plist=dict(
                NSLocationWhenInUseUsageDescription="Need access to location"
           )
        )
     )
)
```

**Comment by Oleksii-Svintsitskyi** [comment]
@ronaldoussoren thank you a lot! it actually works!

The only thing that I'd like to mention, 

is that when you run your application like:
`open -a dist/MyApp.app`
everything works fine, though logs go to Console. 

But when you run application like:
`./dist/MyApp.app/Contents/MacOS/MyApp` 
logs go to terminal, but bssid is empty again.

Is it possible to redirect logs to terminal or make it work with the second call?

**Comment by tejaskumark** [comment]
@Oleksii-Svintsitskyi Can you please give me some more info on how to get BSSID with the help of enabling location services? Any code reference will help. 

Below is snippet where I am getting blank value

```cwinterface = get_interface_object(interface)
    scan = cwinterface.scanForNetworksWithName_error_("Test-Guest", None)
    for ssid in scan:
        print(ssid.valueForKey_("bssid"))```

**Comment by tejaskumark** [comment]
@Oleksii-Svintsitskyi Can you please help here?

**Comment by Oleksii-Svintsitskyi** [comment]
@tejaskumark 
You need to add these lines to your script before calling any CoreWLAN methods.
```
from CoreLocation import CLLocationManager
CLLocationManager.new().requestAlwaysAuthorization()
```
Then, bundle your script into Mac OS application (py2app or pyinstaller)
Then run your .app application and give location permissions in the Mac OS settings like for any other .app

**Comment by tejaskumark** [comment]
@Oleksii-Svintsitskyi Thanks for the quick response. 
I am confused about ```The only thing I have to note, I had to add all 4 keys: NSLocationAlwaysUsageDescription, NSLocationUsageDescription, NSLocationWhenInUseUsageDescription, NSLocationAlwaysAndWhenInUseUsageDescription``` this part. 
Can you please give me some more info on this one? As I am very new to py2app.
Thanks.

**Comment by tejaskumark** [comment]
@Oleksii-Svintsitskyi I have created one repo with changes you have suggested, https://github.com/tejaskumark/ssid-scan-macos. Still I am  not able to get BSSID value even though I have allowed location service for bssid app created through py2app.
Can you please check and let me know if any mistakes you see there?
Thanks.

**Comment by Oleksii-Svintsitskyi** [comment]
@tejaskumark these flags are not that important after all, I found out. The main thing - to add the code a mentioned above (yesterday), to create an .app and give it a permission
https://support.apple.com/en-gb/guide/mac-help/mh35873/mac

**Comment by tejaskumark** [comment]
@Oleksii-Svintsitskyi I have done that and allowed permission to this app, still I don't see bssid is returned. Mac OS Monterey Version 12.4

Can you please check out my code once https://github.com/tejaskumark/ssid-scan-macos?

**Comment by Oleksii-Svintsitskyi** [comment]
@tejaskumark everything seems fine, sorry, then I can't help you

**Comment by tejaskumark** [comment]
@Oleksii-Svintsitskyi Thanks for all the help you provided. 
@ronaldoussoren Can you please help here if possible?

**Comment by thewade** [comment]
@tejaskumark is your goal to run your script as an app? Or were you just doing it as a workaround to the permission issue?The script you have posted to github runs properly for me when called directly with Python interpreter. 

When running directly with the Python interpreter in order to see the BSSID I needed to grant location services permissions to Python itself.

You won't be able to grant location services permissions to Python until you make a call the requires it. This script generated a permission prompt for me with MacOS 13.2:

```
import CoreLocation
from time import sleep

location_manager = CoreLocation.CLLocationManager.alloc().init()
location_manager.startUpdatingLocation()

max_wait = 60
# Get the current authorization status for Python
for i in range(1, max_wait):
    authorization_status = location_manager.authorizationStatus()
    if authorization_status == 3 or authorization_status == 4:
        print("Python has been authorized for location services")
        break
    if i == max_wait-1:
        exit("Unable to obtain authorization, exiting")
    sleep(1)

coord = location_manager.location().coordinate()
lat, lon = coord.latitude, coord.longitude
print("Your location is %f, %f" % (lat, lon))
```

If you don't see the prompt after running the script check the location services privacy settings and see if python is now an option and to enable it.

Now that Python has the correct permissions I can call your script without issue:

```
% python3 bssid.py en0 example_ssid
<CWNetwork: 0x600003888d80> [ssid=example_ssid, bssid=70:3a:xx:xx:xx:xx security=WPA2 Enterprise, rssi=-43, channel=<CWChannel: 0x6000038845a0> [channelNumber=48(5GHz), channelWidth={80MHz}], ibss=0]

```

Hope this helps.

**Comment by tejaskumark** [comment]
@thewade Thanks for informing. It looks like somehow on Mac OS 13.x we are able to get BSSID with granting location services access to Python(Checked onto my Mac OS 13.x). But same is not working for Mac OS 11.x.

**Comment by tejaskumark** [comment]
@thewade Do you have any experience with code signing part for executable? I am working on project where I am creating golang executable binary to get BSSID but some how it is returning null on 13.x as well.
