### ISSUE TITLE
NSAttrbutedText object output's a raw string instead of rich text in my NSTextField

### ISSUE THREAD

**Issue by leifadev** [ronaldoussoren/pyobjc#514]
**Describe the bug**
Having trouble implementing NSAttributedText into a NSTextField. The NSAttributedText set with `setAttributedString_(x)` is outputting plain text of the object itself. Heres what happens instead of the text being bold, centered, etc.:
<img src="https://i.stack.imgur.com/SZS1X.png" height="300" width="350"/>

**Platform information**

* Python version: 3.9.2
* How was python installed: python.org `/Users/leif/PycharmProjects/shoutout/venv/bin/python3`
* macOS version: 13.0.1

**To Reproduce**
```py
html = """<p><b>Word</b> - English</p>
<p><i>Phonetics</i> - Noun</p>
<p><i>A love this word!</i></p>
<p>Definition - An abstraction</p>
"""
new_html = str.encode(html) # Turn html into byte code for NSData

# Make an NSData object with the html string in it
html = Cocoa.NSData.alloc().initWithBytes_length_(new_html, len(new_html))

# Make an instance of an Attributed String
attrString = Foundation.NSAttributedString.alloc().init()

# Instantiate attributed string with the NSData html string
definition = attrString.initWithHTML_documentAttributes_(html, None)
self.definitionField.setAttributedStringValue_(definition)
```
Am I doing something wrong? I've looked everywhere on the web, cant seem to find a forum post with my problem too.

**Expected behavior**
A formatted bolded, italic paragraphed text from my `html` string in the NSTextField

**Additional context**
https://stackoverflow.com/questions/74408371/nsattrbutedtext-object-outputs-a-raw-string-instead-of-rich-text-in-my-nstextfi

**Comment by ronaldoussoren** [comment]
One thing that's not correct is this:

```python3

# Make an instance of an Attributed String
attrString = Foundation.NSAttributedString.alloc().init()

# Instantiate attributed string with the NSData html string
definition = attrString.initWithHTML_documentAttributes_(html, None)
```

This creates an NSAttributedString and then reinitialises it. That's not generally supported by Cocoa classes. The two lines can be combined:

```python3

definition = Foundation.NSAttributedString.initWithHTML_documentAttributes_(html, None)
```

Other than that the code looks fine. 

Something that can cleans up the code a bit: a bytes object in Python is proxied into Objective-C as an NSData instance, you don't have to create an NSData instance by hand.

**Comment by ronaldoussoren** [comment]
I found the problem. The method ``-[NSAttributedString initWithHTML: documentAttributes:]`` has an in-out argument for the second argument, that is in Objective-C the second argument is a pointer to an object (``NSDictionary**``), and the point-to value will be updated by the method.

Python does not have pass-by-reference arguments, but basically uses multiple return values though tuples to get the same effect. Because of that the Python mapping of the method returns a tuple of two arguments: the actual attributed string and the value of the document attributes.

The effect your seeing is Cocoa helpfully transforming said tuple to a string and showing it, giving you the debug representation of the tuple as the value for the label.

To fix this unpack the tuple and ignore the second value:

```python3
html = b"<b>hello</b> world"
definition, _ = Foundation.NSAttributedString.initWithHTML_documentAttributes_(html, objc.NULL)
```

I'm also passing ``objc.NULL`` instead of ``None`` because that results in passing a NULL pointer for the second argument in Objective-C and for this particular class this is documented as a way to not generate the object holding the attributes.

**Comment by leifadev** [comment]
I would like to have the San Francisco font but `initWithHTML` won't allow me to import it from any CSS. I don't know exactly how how to use the `initWithRTF` one either, since when I tried to get the raw text of a .rtf doc and put it into a rb'' string nothing showed up. I guess I need to do the manual way by making a NSMutableAttributedString
