### ISSUE TITLE
version 8.5.1 - Segmentation fault importing AppKit with Yosemite

### ISSUE THREAD

**Issue by macdeport** [ronaldoussoren/pyobjc#521]
**Describe the bug**
I just did a fresh reinstall of py39-pyobjc @8.5.1_0 without trouble but get the following error when importing AppKit:

```
Python 3.9.16 (main, Dec  7 2022, 02:38:04) 
[Clang 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import AppKit
Segmentation fault: 11

```

**Platform information**

*Python 3.9.16
* How was python installed (python.org, anaconda, homebrew, ...) : MacPorts
* macOS version: Yosemite macOS-10.10.5-x86_64-i386-64bit

**To Reproduce**
` import AppKit`

**Expected behavior**
A clear and concise description of what you expected to happen: no crash as with py39-pyobjc @8.4.1_1

**Additional context**
What action you suggest. You are welcome.
Sorry if this error is not correlated...
Thank you for your commitment to PyObjC

**Comment by ronaldoussoren** [comment]
Does this also happen when installing PyObjC from PyPI?

**Comment by macdeport** [comment]
1. The Python 3.9 MacPorts version has been uninstalled to avoid a conflict.
2. I then installed PyObjC with `pip-3.9` : everything works perfectly.
3. To stay consistent with the choice of the MacPorts library manager, I uninstalled this `PyObjC` version and installed again `py39-pyobjc @8.5.1_0`: this time `AppKit` works perfectly and the version displayed by `objc.__version__` is "9.0" (?)

Thanks for your help.

**Comment by ronaldoussoren** [comment]
If ``objc.__version__`` is 9.0 you're likely still using the version you installed manually instead of the one MacPorts. 

Looking at the Portfile for PyObjC the MacPorts project builds pyobjc using a non-system version of libffi. That's something I don't explicitly support, the testing matrix is large enough already with just supporting the system version of libffi. I will therefore not research why the import crashes when using the MacPorts build.
