### ISSUE TITLE
'VNDetectFaceCaptureQualityRequest' object attribute 'setInputFaceObservations_' is read-only

### ISSUE THREAD

**Issue by AkhilAshrefExa** [ronaldoussoren/pyobjc#531]
**Describe the bug**
Trying to set input face observations for VNDetectFaceCaptureQualityRequest. Raising the error
```
'VNDetectFaceCaptureQualityRequest' object attribute 'setInputFaceObservations_' is read-only 
```

**Platform information**
python 3.9
pip installed all required libraries
macOS 11.5.1

**To Reproduce**
```
handler = make_request_handler(results)
vision_request = Vision.VNDetectFaceCaptureQualityRequest.alloc().initWithCompletionHandler_(handler)
vision_request.setInputFaceObservations_ = face_detect_request.results #This variable can be any for now due to the bug
error = vision_handler.performRequests_error_([vision_request], None)

def make_request_handler(results):
    """ results: list to store results """
    if not isinstance(results, list):
        raise ValueError("results must be a list")

    def handler(request, error):
        if error:
            logger.info('Error! %s', error)
        else:
            logger.info("Process completed succesfully")
    return handler
```

**Expected behavior**
Expected behaviour is that the face observation result should be updated similar to attributes like setRevision_

**Comment by ronaldoussoren** [comment]
```python3

vision_request.setInputFaceObservations_ = face_detect_request.results #This variable can be any for now due to the bug
```

This line is wrong and should be:

```python3
vision_request.setInputFaceObservations_(face_detect_request.results)
```

``setInputFaceObservations_`` is a method that should be called. 

Sadly I haven't found a way yet make it possible to use attribute access for getting/setting properties without breaking loads of existing code.  The problem here is that Objective-C has separate namespaces for properties access and method calls, while python does not. Making something like ``inputFaceObservations`` a Python property would therefore break existing code.  That said, I'm seriously considering doing just that in PyObjC 10 and 11 (with 10 adding an option for enabling properties, and 11 enabling that by default).

**Comment by AkhilAshrefExa** [comment]
Thank you for your input.
