### ISSUE TITLE
Get the percentage of charge from the paired device

### ISSUE THREAD

**Issue by Alexandro1112** [ronaldoussoren/pyobjc#545]
Showed an error and a warning when I tried to get the battery of the paired device charged.
I have written a script that detects the battery of a Bluetooth device by address.
Earlier I loaded the IOBluetoothDevice class from the IOBluetooth framework.

```
import objc
import CoreBluetooth 

objc.loadBundleFunctions(
objc.loadBundle("IOBluetooth", globals(),
bundle_path=objc.pathForFramework(u'/System/Library/Frameworks/IOBluetooth.framework')),
globals(),
[('IOBluetoothPreferenceGetControllerPowerState', b'oI'),
 ('IOBluetoothPreferenceSetControllerPowerState', b'Vi'),
 ('IOBluetoothDevice', b'B')]
 )


battery = IOBluetoothDevice.alloc().init().batteryLevel_(0x7f88e9cfa810)
print(battery)
```
Information about the platform

* 3.10
*  python.org
* 11.7.4
<p>Expected behavior<p>
The battery percentage of the paired device should be returned, or although something.
Bellow, error.

```
Traceback (most recent call last):
  File "/Users/admin/PycharmProjects/pythonProject3/BluetoothObjC.py", line 16, in <module>
    battery = IOBluetoothDevice.alloc().init().batteryLevel_(0x7f88e9cfa810)
TypeError: Argument 2 is a block, but no signature available
```

Additional context
I used the ``IOBluetooth.arm64efile.bridgesupport`` file. There I have to
use class `` IOBluetoothDevice``.

```

<class name='IOBluetoothDevice'>
<method selector='isConnected'>
<retval type64='B'/>
</method>
```

**Comment by ronaldoussoren** [comment]
1. Use "import IOBluetooth" instead of the code you use to load the framework, the provided framework bindings add metadata needed to use the APIs and expose constants and the like.
2. AFAIK ``-[IOBluetoothDevice batteryLevel:]`` is not a public API, hence the lack of metadata to allow using blocks

The bridgesupport files shipped with macOS are broken (and have been for a long time) and are not used by PyObjC's framework bindings for that reason.

**Comment by Alexandro1112** [comment]
How to use Iobluetooth with supporting api?
