### ISSUE TITLE
Install doesn't work when running from outside repo dir

### ISSUE THREAD

**Issue by thewh1teagle** [ronaldoussoren/pyobjc#579]
When running 
`python3 pyobjc/install.py` it gives error which it doesn't find files in `development` folder
Only if running it from `pyobjc` folder it finds
On `MacOS` `13.5`

**Comment by thewh1teagle** [comment]
Of course I tried first with pip, it didn't worked.
Also the install.py took long time and eventually failed.

**Comment by ronaldoussoren** [comment]
I cannot easily test 13.5 on M1, but did test on 13.6 on Intel. 

``pip install pyobjc`` worked for me when using fresh virtual environments (``python3.x -m venv ...``) when using either python3.10 (installed from python.org) or /usr/bin/python3 (from Xcode 13.4).

I haven't tested building from source yet,  that might be broken for the current release because of #572 (which is already fixed in the repository).  My current plan is to do more build tests when preparing for the next release.

**Comment by thewh1teagle** [comment]
It's shame that developers needs to struggle with Apple hardware
